# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='photo',
            field=models.FileField(default='44', upload_to=''),
        ),
    ]
