# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170830_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dane',
            name='photo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
