# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20170831_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dane',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='dane',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='dane',
            name='street',
            field=models.CharField(default='', max_length=50, verbose_name='Ulica i numer mieszkania'),
        ),
    ]
