# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170831_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dane',
            old_name='username',
            new_name='owner',
        ),
    ]
