# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170831_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E mail taki długi jak życ'),
        ),
        migrations.AlterField(
            model_name='dane',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='Nazwisko nazwisko też niczego sobie ogogogogo'),
        ),
    ]
