# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170928_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='dane',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='dane',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
